#!/usr/bin/env bash

function __install_r() {

  if ! command -v R >/dev/null 2>&1; then
    if __ubuntu; then
      sudo apt install -y dirmngr gnupg apt-transport-https ca-certificates software-properties-common
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
      sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
      sudo apt update
      sudo apt install -y r-base
      R --version

    elif __osx; then
      noop

    else
      echo "$OSTYPE" is not supported at this time.
    fi

  else

    if __ubuntu; then
      sudo update
      sudo apt upgrade -y r-base
      R --version

    else
      echo "$OSTYPE" is not supported at this time.
    fi

  fi
}
