#!/usr/bin/bash
function __install_jetbrains() {

mkdir -p $HOME/bin
wget -q https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.18.7609.tar.gz -O - | tar zxvf - -C /tmp
mv /tmp/jetbrains-toolbox*/jetbrains-toolbox  $HOME/bin/

sudo apt install -y libnss3 libatk1.0-dev libatk-bridge2.0-dev xfce4

}