#!/usr/bin/bash

if ! command -v R >/dev/null 2>&1; then
  if __ubuntu; then
    sudo apt install -y dirmngr gnupg apt-transport-https ca-certificates software-properties-common
    sudo apt-key adv  --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
    sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
    sudo apt install -y r-base
    R --version

  elif __osx; then
    echo "$OSTYPE" is not supported at this time.
  else
    echo "$OSTYPE" is not supported at this time.
  fi

fi
