#!/usr/bin/env bash

function __brew_bundle() {

  if ! command -v brew >/dev/null 2>&1; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  if __osx; then
    brew bundle install --file "${CONFIGURATION_DIR}"/Brewfile
  else
    cat "${CONFIGURATION_DIR}"/apt.txt | tr -s '\n' ' ' | xargs sudo apt install -y
  fi

}

function __install_python3() {

  if [[ ! -d $HOME/.env3 ]]; then

    python3 -m venv $HOME/.env38
    source $HOME/.env38/bin/activate
    ln -s $HOME/.env38 $HOME/.env3
  fi

  python3 -m pip install --upgrade pip
  python3 -m pip install -r ${CONFIGURATION_DIR}/requirements.txt

}