#!/usr/bin/env bash
function __install_golang() {
  root_var=''
  if ! command -v go >/dev/null 2>&1; then
    if __ubuntu; then
      sudo apt install wget -y
      latest_version=$(curl 'https://golang.org/VERSION?m=text')
      sudo wget -q https://golang.org/dl/${latest_version}.linux-amd64.tar.gz -O - | sudo tar zxvf - -C /usr/local
      curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1

    elif __osx; then
      echo 'noop' >/dev/null
    fi
  fi

  if __ubuntu; then
    root_var='/usr/local/go'

  elif __osx; then
    root_var='/usr/local/var/homebrew/linked/go/'
  fi

  shellName=$(basename ${SHELL})
  case ${shellName} in

  zsh)
    shellProfileScript="${HOME}/.zshrc"
    ;;

  bash)
    shellProfileScript="${HOME}/.bashrc"
    ;;

  esac


  if ! grep -Fq 'export GOROOT=' ${shellProfileScript}; then
    echo " " >>"${shellProfileScript}"
    echo "export GOROOT=$root_var" >>"${shellProfileScript}"
  fi

  if ! grep -Fq 'export GOPATH=' "${shellProfileScript}"; then
    echo 'export GOPATH=$HOME/go' >>"${shellProfileScript}"
  fi

  if ! grep -Fq 'export PATH=$GOPATH' ${shellProfileScript}; then
    echo 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH' >>"${shellProfileScript}"
  fi



}