#!/usr/bin/env bash



function __install_jdk() {


    if __ubuntu; then
      sudo apt-get install -y software-properties-common
      wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
      sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
      sudo apt-get update
      sudo apt install -y adoptopenjdk-15-hotspot adoptopenjdk-11-hotspot openjdk-13-jdk

    elif __osx; then
      noop
    else
      echo "$OSTYPE" is not supported at this time.
    fi


}