#!/usr/bin/env bash

function __brew_bundle() {

  # /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  if __osx; then
    brew bundle install --file ${CONFIGURATION_DIR}/Brewfile
  else
    sudo apt install -y $(cat ${CONFIGURATION_DIR}/apt.txt)
  fi

}

function __install_python3() {

  if ! command -v python3 >/dev/null 2>&1; then
    if __ubuntu; then
      sudo apt update
      sudo apt install python3-virtualenv python3-venv -y
      sudo apt upgrade python3-virtualenv python3-venv -y

    elif __osx; then
      echo 'noop' >/dev/null
    else
      echo "$OSTYPE" is not supported at this time.
    fi

  else

    if __ubuntu; then
      sudo apt update
      sudo apt upgrade python3-virtualenv python3-venv -y
    elif __osx; then
      noop
    else
      echo "$OSTYPE" is not supported at this time.
    fi

    python3 -m pip install --upgrade virtualenv pip
    python3 -m pip install --upgrade -r ${CONFIGURATION_DIR}/requirements.txt

  fi

  if [[ ! -d $HOME/.env3 ]]; then

    python3 -m venv $HOME/.env39
    source $HOME/.env39/bin/activate
    ln -s $HOME/.env39 $HOME/.env3
  fi

  python3 -m pip install --upgrade pip
  python3 -m pip  install -r ${CONFIGURATION_DIR}/requirements.txt



}