#!/usr/bin/env bash

function __install_ruby() {

  if ! command -v ruby >/dev/null 2>&1; then

    if __osx; then
      eval "$(rbenv init -)"
      rbenv install 3.0.0
      rbenv install 2.7.1

      RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
    else
      curl -fsSL https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-installer | bash
      eval "$(rbenv init -)"

      shellName=$(basename ${SHELL})
      case ${shellName} in

      zsh)
        shellProfileScript="${HOME}/.zshrc"
        ;;

      bash)
        shellProfileScript="${HOME}/.bashrc"
        ;;

      esac

      if [ $(grep -cF 'PATH=$PATH:$HOME/.rbenv/bin' "${shellProfileScript}") -lt 1 ]; then
        echo 'export PATH=$PATH:$HOME/.rbenv/bin' >>"${shellProfileScript}"]
      fi

      $HOME/.rbenv/bin/rbenv install 3.0.0
      $HOME/.rbenv/bin/rbenv install 2.7.1

    fi

  else

    if __ubuntu; then
      sudo apt upgrade -y libnss3 libatk1.0-dev libatk-bridge2.0-dev xfce4

    elif __osx; then
      noop
    else
      echo "$OSTYPE" is not supported at this time.
    fi
  fi

}
