#!/usr/bin/env bash

function __brew_bundle() {

  if __osx; then
    brew bundle install --file ${CONFIGURATION_DIR}/Brewfile
  fi

}

function __install_python3() {

  if ! command -v python3 >/dev/null 2>&1; then
    if __ubuntu; then
      sudo apt update
      sudo apt install python3-virtualenv python3-venv -y
      sudo apt upgrade python3-virtualenv python3-venv -y


    elif __osx; then
      echo 'noop' >/dev/null
    else
      echo "$OSTYPE" is not supported at this time.
    fi

    pip install virtualenv
    pip install --upgrade pip
    pip install -r ${CONFIGURATION_DIR}/requirements.txt

  else

    if __ubuntu; then
      sudo apt update
      sudo apt upgrade python3-virtualenv python3-venv -y
    elif __osx; then
      noop
    else
      echo "$OSTYPE" is not supported at this time.
    fi

    pip install --upgrade virtualenv pip
    pip install --upgrade -r ${CONFIGURATION_DIR}/requirements.txt

  fi

  pip install --upgrade virtualenv pip
  python3 -m venv $HOME/.env3
  source $HOME/.env3/bin/activate
  pip install --upgrade pip
  pip install --upgrade -r ${CONFIGURATION_DIR}/requirements.txt
}
