#!/bin/bash


valid_values=("client tw personal")
read -r -d '' __helptext <<-'EOF' || true # exits non-zero when EOF encountered
 Configure AWS access roles.
EOF

[[ "${__usage+x}" ]] || read -r -d '' __usage <<-'EOF' || true # exits non-zero when EOF encountered
  -p --profile  [arg] Profile to configure. Valid values: [client, tw, personal]. Required.
EOF


source $ROOT_DIR/_boilerplate.sh

# shellcheck disable=SC2076
[[ " ${valid_values[*]} " =~ " ${arg_p:-} " ]] || help

case "${arg_p}" in


  client)

  stars=$(printf '*%.0s' {1..20})
  aws configure set region us-east-1 --profile client
  aws configure --profile client

  aws configure set region "$(aws configure get region --profile client)" --profile clientmfa


  read -p "MFA Arn [$(aws configure get serial-number --profile client | sed -e "s/^.\{20\}/${stars}/g")]: " mfaArn
  mfaArn=${mfaArn:-$(aws configure get serial-number --profile client)}
  aws configure set serial-number --profile client $mfaArn

  read -p "Assumed Role Arn [$(aws configure get role-arn --profile client | sed -e "s/^.\{20\}/${stars}/g")]: " roleArn
  roleArn=${roleArn:-$(aws configure get role-arn --profile client)}
  aws configure set role-arn --profile client $roleArn

  read -p "Account Number [$(aws configure get account-number --profile client | sed -e 's/^......./*******/g')]: " roleArn
  roleArn=${roleArn:-$(aws configure get account-number --profile client)}
  aws configure set account-number --profile client $roleArn
  ;;

tw)

  set -e

  aws configure set region us-east-1 --profile tw

  read -p "AWS Okta App Id [$(aws configure get tw-app-id --profile tw)]: " twAppId
  twAppId=${twAppId:-$(aws configure get tw-app-id --profile tw)}
  aws configure set tw-app-id --profile tw $twAppId

  read -p "Okta username [$(aws configure get username --profile tw)]: " username
  username=${username:-$(aws configure get username --profile tw)}
  aws configure set username --profile tw $username

  ;;


  personal)


  stars=$(printf '*%.0s' {1..20})
  aws configure set region us-east-1 --profile personal
  aws configure --profile personal

  aws configure set region "$(aws configure get region --profile personal)" --profile personalmfa


  read -p "MFA Arn [$(aws configure get serial-number --profile personal | sed -e "s/^.\{20\}/${stars}/g")]: " mfaArn
  mfaArn=${mfaArn:-$(aws configure get serial-number --profile personal)}
  aws configure set serial-number --profile personal $mfaArn

  read -p "Assumed Role Arn [$(aws configure get role-arn --profile personal | sed -e "s/^.\{20\}/${stars}/g")]: " roleArn
  roleArn=${roleArn:-$(aws configure get role-arn --profile personal)}
  aws configure set role-arn --profile personal $roleArn

  read -p "Account Number [$(aws configure get account-number --profile personal | sed -e 's/^......./*******/g')]: " roleArn
  roleArn=${roleArn:-$(aws configure get account-number --profile personal)}
  aws configure set account-number --profile personal $roleArn
  ;;
esac
