#!/bin/bash

read -r -d '' __helptext <<-'EOF' || true                      # exits non-zero when EOF encountered
 Scan for secret leaks.
EOF

[[ "${__usage+x}" ]] || read -r -d '' __usage <<-'EOF' || true # exits non-zero when EOF encountered
  -s --secret-pattern-file  [arg] Comma-separated list of files containing secret string patterns. Required.
  -r --repo-path            [arg] Path to Git repo to inspect. Required.
EOF

source $ROOT_DIR/_boilerplate.sh

files=$(git diff --name-only --cached)
for i in $(echo "${arg_s}" | sed "s/,/ /g"); do
  # call your procedure/other scripts here below
  set +o errexit
  grep -iEn -f $i ${files[@]}
  status=$?
  if $(exit $status); then
    exit 1
  fi
done
