#!/usr/bin/env bash

use install-zsh-plugins
use install-awscli
use install-cli-tools
use install-golang
use install-ides
use install-k8s-tools
use install-okta
use install-r
use install-python3
use install-ruby

read -r -d '' __helptext <<-'EOF' || true # exits non-zero when EOF encountered
 Install development tools.
EOF

[[ "${__usage+x}" ]] || read -r -d '' __usage <<-'EOF' || true # exits non-zero when EOF encountered
  -i --install      Install tools.
  -r --reinstall    Re-install.
EOF

source $ROOT_DIR/_boilerplate.sh

if [[ "${arg_r:?}" = "1" ]]; then
  echo "Deleting..."
  sudo rm -rfv /usr/local/bin/eksctl
  sudo rm -rfv /usr/local/bin/kube
  sudo rm -rfv /usr/local/bin/helm
  sudo rm -rfv /usr/local/bin/fluxctl
  sudo rm -rfv /usr/local/bin/tkn
  sudo rm -rfv /usr/local/go
fi

if [[ "${arg_i:?}" -gt 0 ]]; then

  mypwd=$PWD
  set -e

  __brew_bundle
  __install_python3
  __install_ruby
  __install_okta
  __install_golang
  __install_k8s_tools
  __install_awscli
  __install_zsh_plugins
  __install_cli_tools
  __install_ides

fi