#!/usr/bin/env bash

use install-zsh-plugins
use install-awscli
use install-cli-tools
use install-golang
use install-jetbrains
use install-k8s-tools
use install-okta
use install-r
use install-python3


valid_values=("eks dev ds")
read -r -d '' __helptext <<-'EOF' || true # exits non-zero when EOF encountered
 Install development tools.
EOF

[[ "${__usage+x}" ]] || read -r -d '' __usage <<-'EOF' || true # exits non-zero when EOF encountered
  -i --install  [arg] Toolkit to install. Valid values: [eks, dev, ds]. Required.
  -r --reinstall      Re-install.
EOF


source $ROOT_DIR/_boilerplate.sh

# shellcheck disable=SC2076
[[ " ${valid_values[*]} " =~ " ${arg_i:-} " ]] || help


case "${arg_i}" in

eks)

  if [[ "${arg_r:?}" = "1" ]]; then
    sudo rm -rf /usr/local/bin/eksctl
    sudo rm -rf /usr/local/bin/kubectl
    sudo rm -rf /usr/local/bin/helm
    sudo rm -rf /usr/local/bin/fluxctl
    sudo rm -rf /usr/local/bin/tkn
    sudo rm -rf /usr/local/go
  fi

  mypwd=$PWD
  set -e

  __install_python3
  __install_okta
  __install_golang
  __install_k8s_tools
  __install_awscli

  ;;

dev)

  if [[ "${arg_r:?}" = "1" ]]; then
    sudo rm -rf /usr/local/go
  fi

  __install_zsh_plugins
  __install_python3
  __install_golang
  __install_cli_tools

  ;;

ds)

  __install_python3
  pip install --upgrade -r ${CONFIGURATION_DIR}/requirements.txt
  __install_r
  __install_jetbrains

  ;;

esac
