apiVersion: v1
data:
  ***REMOVED***-uptime.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 3,
      "links": [],
      "panels": [
        {
          "datasource": "Prometheus",
          "gridPos": {
            "h": 9,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 7,
          "options": {
            "fieldOptions": {
              "calcs": [
                "mean"
              ],
              "defaults": {
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "semi-dark-red",
                      "value": null
                    },
                    {
                      "color": "#EAB839",
                      "value": 0.8
                    },
                    {
                      "color": "dark-green",
                      "value": 0.97
                    }
                  ]
                },
                "unit": "percentunit"
              },
              "overrides": [],
              "values": false
            },
            "orientation": "auto",
            "showThresholdLabels": false,
            "showThresholdMarkers": true
          },
          "pluginVersion": "6.6.2",
          "targets": [
            {
              "expr": "avg(avg_over_time(probe_success[1h])) by(job)",
              "hide": false,
              "instant": false,
              "legendFormat": "Uptime",
              "refId": "B"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Overall System Uptime",
          "type": "gauge"
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Prometheus",
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 9,
            "w": 12,
            "x": 0,
            "y": 9
          },
          "hiddenSeries": false,
          "id": 2,
          "interval": "",
          "legend": {
            "avg": false,
            "current": true,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "dataLinks": []
          },
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [
            {
              "alias": "Uptime"
            }
          ],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "avg_over_time(probe_success{instance=\"https://***REMOVED***.***REMOVED***.k8.***REMOVED***.com/heartbeat\"}[5m]) ",
              "hide": false,
              "instant": false,
              "legendFormat": "Uptime (Trailing 5 min)",
              "refId": "B"
            },
            {
              "expr": "avg_over_time(probe_success{instance=\"https://***REMOVED***.***REMOVED***.k8.***REMOVED***.com/heartbeat\"}[30m]) ",
              "hide": false,
              "instant": false,
              "legendFormat": "Uptime (Trailing 30 min)",
              "refId": "A"
            },
            {
              "expr": "avg_over_time(probe_success{instance=\"https://***REMOVED***.***REMOVED***.k8.***REMOVED***.com/heartbeat\"}[1h]) ",
              "hide": false,
              "instant": false,
              "legendFormat": "Uptime (Trailing 1 hour)",
              "refId": "C"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Devhub Uptime",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "decimals": null,
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": "1",
              "min": ".7",
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": "1",
              "min": ".7",
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Prometheus",
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 9,
            "w": 12,
            "x": 12,
            "y": 9
          },
          "hiddenSeries": false,
          "id": 6,
          "interval": "",
          "legend": {
            "avg": false,
            "current": true,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "dataLinks": []
          },
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [
            {
              "alias": "Uptime"
            }
          ],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "avg_over_time(probe_success{instance=\"https://tekton-dashboard.***REMOVED***.k8.***REMOVED***.com\"}[5m])",
              "hide": false,
              "instant": false,
              "legendFormat": "Uptime (Trailing 5 mins)",
              "refId": "B"
            },
            {
              "expr": "avg_over_time(probe_success{instance=\"https://tekton-dashboard.***REMOVED***.k8.***REMOVED***.com\"}[30m])",
              "hide": false,
              "instant": false,
              "legendFormat": "Uptime (Trailing 30 mins)",
              "refId": "A"
            },
            {
              "expr": "avg_over_time(probe_success{instance=\"https://tekton-dashboard.***REMOVED***.k8.***REMOVED***.com\"}[1h])",
              "hide": false,
              "instant": false,
              "legendFormat": "Uptime (Trailing 1 hour)",
              "refId": "C"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Tekton Dashboard Uptime",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "decimals": null,
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": "1",
              "min": ".7",
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Prometheus",
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 9,
            "w": 12,
            "x": 0,
            "y": 18
          },
          "hiddenSeries": false,
          "id": 4,
          "interval": "",
          "legend": {
            "avg": false,
            "current": true,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "dataLinks": []
          },
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [
            {
              "alias": "Uptime"
            }
          ],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "avg_over_time(probe_success{instance=\"https://jaeger.***REMOVED***.k8.***REMOVED***.com/api/services\"}[5m])",
              "hide": false,
              "instant": false,
              "legendFormat": "Uptime (Trailing 5 min)",
              "refId": "B"
            },
            {
              "expr": "avg_over_time(probe_success{instance=\"https://jaeger.***REMOVED***.k8.***REMOVED***.com/api/services\"}[30m])",
              "hide": false,
              "instant": false,
              "legendFormat": "Uptime (Trailing 30 min)",
              "refId": "A"
            },
            {
              "expr": "avg_over_time(probe_success{instance=\"https://jaeger.***REMOVED***.k8.***REMOVED***.com/api/services\"}[1h])",
              "hide": false,
              "instant": false,
              "legendFormat": "Uptime (Trailing 1 hour)",
              "refId": "C"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Jaeger Uptime",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "decimals": null,
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": "1",
              "min": ".7",
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Prometheus",
          "decimals": null,
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 9,
            "w": 12,
            "x": 12,
            "y": 18
          },
          "hiddenSeries": false,
          "id": 5,
          "interval": "",
          "legend": {
            "avg": false,
            "current": true,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "dataLinks": []
          },
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [
            {
              "alias": "Uptime"
            }
          ],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "avg_over_time(probe_success{instance=\"https://sonar.***REMOVED***.k8.***REMOVED***.com\"}[5m])",
              "hide": false,
              "instant": false,
              "legendFormat": "Uptime (Trailing 5 min)",
              "refId": "B"
            },
            {
              "expr": "avg_over_time(probe_success{instance=\"https://sonar.***REMOVED***.k8.***REMOVED***.com\"}[30m])",
              "hide": false,
              "instant": false,
              "legendFormat": "Uptime (Trailing 30 min)",
              "refId": "A"
            },
            {
              "expr": "avg_over_time(probe_success{instance=\"https://sonar.***REMOVED***.k8.***REMOVED***.com\"}[1h])",
              "hide": false,
              "instant": false,
              "legendFormat": "Uptime (Trailing 1 hour)",
              "refId": "C"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Sonar Uptime",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": "1",
              "min": ".7",
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        }
      ],
      "refresh": false,
      "schemaVersion": 22,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ]
      },
      "timezone": "",
      "title": "Devhub Services Uptime",
      "uid": "c5xipSuWk",
      "version": 2
    }
kind: ConfigMap
metadata:
  labels:
    app: prometheus-operator-grafana
    chart: prometheus-operator-8.12.1
    grafana_dashboard: "1"
    heritage: Tiller
    release: prom-operator
  name: ***REMOVED***-uptime
  namespace: monitoring
