name: cloudwatchlogsbeat

cloudwatchlogsbeat:

  # === GENERAL SETTINGS ===
  # the bucket in which log streams save their state
  s3_bucket_name: cloudwatchlogsbeat-state
  # s3 key prefix (default: "")
  s3_key_prefix: prefix/
  # Defines how often the manager will refresh its list of monitored log groups
  # AWS API call: DescribeLogGroups
  group_refresh_frequency: 10s
  # defines how often a log group will refresh its list of monitored streams
  # AWS API call: DescribeLogStreams
  stream_refresh_frequency: 5s
  # defines how often groups, streams and the group manager log their reporting metrics
  report_frequency: 5m
  # defines AWS region (default: eu-west-1)
  aws_region: us-east-1

  # === HOT STREAMS ===
  # hot streams are streams whose last event is earlier than this value
  # a value of zero deactivates hot streams
  hot_stream_event_horizon: 5m
  # defines the refresh frequency of log events for hot streams
  # AWS API call: GetLogEvents
  hot_stream_event_refresh_frequency: 1s

  # === STANDARD STREAMS ===
  # log events earlier than this value are not captured
  # log streams whose last event is earlier than this value are not monitored
  stream_event_horizon: 3h
  # defines the refresh frequency of log events for streams
  # AWS API call: GetLogEvents
  stream_event_refresh_frequency: 10s

  # === PROSPECTORS ===
  # Applications whose log groups we'd like to monitor
  prospectors:
    # the id will be used as the _type field
    - id: application-name
      # which log groups to monitor for this application
      groupnames:
        - /aws/eks/*
        # - /aws/lambda/another-name-*
      # multiline settings [OPTIONAL]
      # Check: https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#multiline
      multiline:
        pattern: "^REPORT RequestId.+"
        negate: true
        match: before

output.elasticsearch:
  host: '${NODE_NAME}'
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'