[kubernetes]
style = "green"
disabled = false

[memory_usage]
disabled = true
show_percentage = true
show_swap = true
threshold = -1
symbol = "Mem: "
separator = "/"
style = "bold dimmed green"


[time]
disabled = false
format = "[\\[ $time \\]]($style)"
utc_time_offset = "local"

#
#[custom.assume_role]
#shell = ["/usr/bin/zsh"]
#when = "exit 0"
#command = "devcli role-session --time-left"
#style = "bold green"
#format = "[AWS: $output]($style)"
#
#[custom.assume_role_expired]
#shell = ["/usr/bin/zsh"]
#when = "devcli role-session --time-expired"
#command = "echo AWS"
#style = "bold red"
#format = "[AWS ]($style)"

[custom.blank]
format=" "
shell=["/usr/bin/zsh"]
when = "exit 0"
command ="echo lol"

[helm]
disabled = false
