# Don't print a new line at the start of the prompt
add_newline =  false

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
#symbol = "➜"     # The "symbol" segment is being set to "➜"

# Disable the package module, hiding it from the prompt completely
[package]
#disabled = false


[kubernetes]
style = "dimmed green"
disabled = false
#symbol = "⛵ "
symbol =""

[aws]
style = "bold yellow"
displayed_items= "all"
disabled = false

#[aws.region_aliases]
# ap-southeast-2 = "au"
# us-east-1 = "ue1"
# us-east-2 = "ue2"
# us-west-1 = "uw1"
