[kubernetes]
style = "green"
disabled = false

[memory_usage]
disabled = true
show_percentage = true
show_swap = true
threshold = -1
symbol = "Mem: "
separator = "/"
style = "bold dimmed green"

[python]
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style) '

[time]
disabled = false
format = "[\\[ $time \\]]($style)"
utc_time_offset = "local"


[custom.assume_role]
shell = ["/usr/bin/zsh"]
when = "devcli role-session --time-left"
command = "devcli role-session --time-left"
format = "[AWS:](120) $output "

[custom.assume_role_expired]
shell = ["/usr/bin/zsh"]
when = "devcli role-session --time-expired"
command = "echo AWS"
style = "bold red"
format = "[AWS ]($style)"

[custom.git]
style = "bold 172"
format = "[\\[$output\\]]($style) "
when = "exit 0"
command = "devcli git-pair"

[helm]
disabled = false

[java]
style = "red"


[aws]
symbol = "☁️ "
